### ISSUE TITLE
Not compatible with HF patch

### ISSUE THREAD

**Issue by toydev** [toydev/HC_VRTrial#8]
Unity.XR.OpenVR.OpenVRHelpers.GetType Influenced by com.rlabrecque.steamworks.net.

```
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Exception: SteamVR initialization error.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'OptionValue' from assembly 'com.rlabrecque.steamworks.net, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Unity.XR.OpenVR.OpenVRHelpers.<>c.<GetType>b__2_4(Assembly assembly)
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Unity.XR.OpenVR.OpenVRHelpers.GetType(String className, Boolean fullname)
   at Unity.XR.OpenVR.OpenVREvents..ctor(Boolean lazyLoadEvents)
   at Unity.XR.OpenVR.OpenVREvents.Initialize(Boolean lazyLoadEvents)
   at Unity.XR.OpenVR.OpenVRLoader.Initialize()
   at HC_VRTrial.VRUtils.VR.Setup()+MoveNext()
```

**Comment by toydev** [comment]
Added exception handling assuming that a dll with an invalid format is included.

1bb80a9817f37d31268e175c137acaefc8466a69
